serial_number: a200-0000
version: 0
system:
  hosts:
    - hostname: cpr-a200-0000
      ip: 192.168.131.1
  ros2:
    namespace: a200_0000
platform:
  attachments:
    - name: front_bumper
      type: a200.bumper
      parent: front_bumper_mount
    - name: rear_bumper
      type: a200.bumper
      parent: rear_bumper_mount
    - name: top_plate
      type: a200.top_plate
  mcu:
    protocol: proton
manipulators:
  arms:
    - model: universal_robots
      parent: default_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ur_type: ur5e
      robbot_ip: 192.168.131.40
      headless_mode: false
      kinematics_parameters_file: "$(find ur_description)/config/ur5e/default_kinematics.yaml"
      poses:
        - name: custom
          joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]
      gripper:
        model: robotiq_2f_85
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
sensors:
  lidar2d:
    - model: hokuyo_ust
      urdf_enabled: true
      launch_enabled: true
      parent: base_link
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        urg_node:
          laser_frame_id: lidar2d_0_laser
          ip_address: 192.168.131.20
          ip_port: 10940
          angle_min: -2.356
          angle_max: 2.356