title: Kodo ShelfBot
description: Autonomous Warehouse AMR + Manipulator System
theme: jekyll-theme-cayman

baseurl: ""
url: "https://kodorobotics.com/kodoshelfbot"

markdown: kramdown

permalink: /:year/:month/:day/:title/

plugins:
  - jekyll-feed
